name: Birthday Check

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  check-birthdays:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create config files
      env:
        BIRTHDAY_DATA: ${{ secrets.BIRTHDAY_DATA }}
      run: |
        # 直接写入邮箱配置文件
        cat << EOF > email.json
        {
            "sender": {
                "email": "${{ secrets.SENDER_EMAIL }}",
                "password": "${{ secrets.EMAIL_PASSWORD }}",
                "smtp_server": "smtp.qq.com",
                "smtp_port": 465
            },
            "recipients": [
                "${{ secrets.RECIPIENT_EMAIL }}"
            ]
        }
        EOF
        
        # 使用Python处理生日数据的反序列化
        python3 << EOF
        import json
        import os
        
        # 从环境变量获取JSON字符串
        birthday_str = os.environ["BIRTHDAY_DATA"]
        
        # 解析JSON字符串
        birthday_data = json.loads(birthday_str)
        
        # 格式化并写入文件
        with open("birthday.json", "w", encoding="utf-8") as f:
            json.dump(birthday_data, f, ensure_ascii=False, indent=4)
        EOF
      
    - name: Run birthday check
      run: python check_birthdays.py 